<template>
  <div>
    <v-layout wrap row justify-center>
      <v-flex xs3>
        <v-autocomplete v-model="location" :items="locations" item-text="name"
                        item-value="name" menu-props="auto" label="Select Location" hide-details
                        clearable single-line></v-autocomplete>
      </v-flex>
      <v-flex xs3>
        <v-text-field v-model="searchString" placeholder="Search by name or email..."></v-text-field>
      </v-flex>
      <v-flex align-self-center>
        <v-btn icon>
          <v-icon>search</v-icon>
        </v-btn>
      </v-flex>
      <v-flex align-self-center>
        <v-switch v-model="isActive" label="Active" color="primary"></v-switch>
      </v-flex>
      <v-flex align-self-center>
        <v-checkbox v-model="isAll" label="All" color="primary"></v-checkbox>
      </v-flex>
      <v-flex align-self-center>
        <v-switch v-model="isCardType" v-bind:label="getLabel" color="primary"></v-switch>
      </v-flex>
    </v-layout>

    <LearnersCardView :learners="learners" v-if="isCardType" @edit="edit"></LearnersCardView>
    <LearnersTableView :learners="learners" v-else @edit="edit"></LearnersTableView>

    <v-dialog v-model="dialog" width="500">
      <LearnerModal
        :item="selected"
        :isShow="dialog"
        @close="dialog = false"
        @save="save"/>
    </v-dialog>
  </div>
</template>

<script>
import LearnerModal from '../../../components/Modal/LearnerModal'
import LearnersCardView from './LearnersCardView'
import LearnersTableView from './LearnersTableView'

export default {
  name: 'Learners',
  components: { LearnersTableView, LearnersCardView, LearnerModal },
  data: () => ({
    isCardType: false,
    learners: {
      'data': [{
        'id': 492,
        'active': 'yes',
        'name': 'Sohan Reddy',
        'email': 'sohanreddyg@gmail.com',
        'since': 1547323200000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 492, 'location_id': 2 }
        }, {
          'id': 3,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 492, 'location_id': 2 }
        }],
        'code': 'STS0000089',
        'joined_on': '13th Jan 2019',
        'credits': 8,
        'user': {
          'id': 1167,
          'email': 'sohanreddyg@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2019-01-11 17:54:16',
          'updated_at': '2019-01-13 11:51:54',
          'deleted_at': null,
          'name': 'Sohan Reddy',
          'username': 'sohan1',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Physics',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 491,
        'active': 'yes',
        'name': 'Siddharth Tripurani',
        'email': 'sidboss03@gmail.com',
        'since': 1547323200000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 491, 'location_id': 2 }
        }],
        'code': 'STS0000088',
        'joined_on': '13th Jan 2019',
        'credits': 8,
        'user': {
          'id': 1168,
          'email': 'sidboss03@gmail.com',
          'permissions': [],
          'last_login': '2019-01-13 15:13:20',
          'created_at': '2019-01-11 17:56:25',
          'updated_at': '2019-01-13 15:13:20',
          'deleted_at': null,
          'name': 'Siddharth Tripurani',
          'username': 'siddharthtripurani',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Physics',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 489,
        'active': 'yes',
        'name': 'Sristhuthi',
        'email': 'kcsristhuthi@gmail.com',
        'since': 1546200000000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 489, 'location_id': 7 }
        }],
        'code': 'STS0000086',
        'joined_on': '31st Dec 2018',
        'credits': 0,
        'user': {
          'id': 1160,
          'email': 'kcsristhuthi@gmail.com',
          'permissions': [],
          'last_login': '2019-01-12 22:47:53',
          'created_at': '2018-12-30 11:33:54',
          'updated_at': '2019-01-12 22:47:53',
          'deleted_at': null,
          'name': 'Sristhuthi',
          'username': 'sristhuthi',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 488,
        'active': 'yes',
        'name': 'Takalla Vikranth',
        'email': 'temporaryemail@abcd.com',
        'since': 1545422400000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 488, 'location_id': 6 }
        }],
        'code': 'STT0000022',
        'joined_on': '22nd Dec 2018',
        'credits': 9,
        'user': {
          'id': 1151,
          'email': 'temporaryemail@abcd.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-22 16:25:02',
          'updated_at': '2018-12-22 16:25:02',
          'deleted_at': null,
          'name': 'Takalla Vikranth',
          'username': 'takallavikranth',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'English and other subjects',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 487,
        'active': 'yes',
        'name': 'sai chandan k',
        'email': 'konreddysai@gmail.com',
        'since': 1545422400000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 487, 'location_id': 6 }
        }],
        'code': 'STS0000085',
        'joined_on': '22nd Dec 2018',
        'credits': 5,
        'user': {
          'id': 1150,
          'email': 'konreddysai@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-22 16:14:44',
          'updated_at': '2018-12-22 16:14:44',
          'deleted_at': null,
          'name': 'sai chandan k',
          'username': 'saichandank',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 486,
        'active': 'yes',
        'name': 'Rushil Sureen',
        'email': 'kirtisureen@yahoo.co.in',
        'since': 1544904000000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 486, 'location_id': 2 }
        }],
        'code': 'STR0000035',
        'joined_on': '16th Dec 2018',
        'credits': 0,
        'user': {
          'id': 1145,
          'email': 'kirtisureen@yahoo.co.in',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-16 14:32:38',
          'updated_at': '2018-12-16 14:32:38',
          'deleted_at': null,
          'name': 'Rushil Sureen',
          'username': 'rushilsureen',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'English,Math',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 485,
        'active': 'yes',
        'name': 'parthavi reddy',
        'email': 'parthavireddy29@gmail.com',
        'since': 1544472000000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 2 }
        }, {
          'id': 4,
          'name': 'Aham Learning Hub @ Online Engagement',
          'slug': 'aham-learning-hub-at-online-engagement',
          'code': 'ALH0000003',
          'street_address': 'No Real location involved',
          'landmark': 'Not Applicable',
          'city_id': 1,
          'country_id': null,
          'pincode': 500008,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2016-11-02 06:37:35',
          'updated_at': '2016-11-02 06:37:35',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#89E5E3',
          'frontend_slug': 'aham-engagement',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 4 }
        }, {
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 6 }
        }],
        'code': 'STP0000034',
        'joined_on': '11th Dec 2018',
        'credits': 9,
        'user': {
          'id': 1144,
          'email': 'parthavireddy29@gmail.com',
          'permissions': [],
          'last_login': '2018-12-19 00:38:25',
          'created_at': '2018-12-11 16:07:36',
          'updated_at': '2018-12-19 00:38:25',
          'deleted_at': null,
          'name': 'parthavi reddy',
          'username': 'parthavireddy',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'i am interested in biology and chemistry',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 484,
        'active': 'yes',
        'name': 'Lava Panta',
        'email': 'alekyap@yahoo.com',
        'since': 1544212800000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 484, 'location_id': 2 }
        }],
        'code': 'STL0000004',
        'joined_on': '8th Dec 2018',
        'credits': 10,
        'user': {
          'id': 1138,
          'email': 'alekyap@yahoo.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-05 09:58:25',
          'updated_at': '2018-12-05 09:58:25',
          'deleted_at': null,
          'name': 'Lava Premal Reddy Panta',
          'username': 'lavapremalreddypanta',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'Spanish',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 483,
        'active': 'yes',
        'name': 'Nimish Ray',
        'email': 'ray.nimish@gmail.com',
        'since': 1543867200000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 483, 'location_id': 2 }
        }],
        'code': 'STN0000030',
        'joined_on': '4th Dec 2018',
        'credits': 4,
        'user': {
          'id': 1136,
          'email': 'ray.nimish@gmail.com',
          'permissions': [],
          'last_login': '2019-01-13 17:08:41',
          'created_at': '2018-12-03 17:58:23',
          'updated_at': '2019-01-13 17:08:41',
          'deleted_at': null,
          'name': 'Nimish Ray',
          'username': 'nimishray',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Math, Physics, and chemistry',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 482,
        'active': 'yes',
        'name': 'Akhil Gadde',
        'email': 'akhilgadde99@gmail.com',
        'since': 1543867200000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 482, 'location_id': 2 }
        }],
        'code': 'STA0000092',
        'joined_on': '4th Dec 2018',
        'credits': 0,
        'user': {
          'id': 1137,
          'email': 'akhilgadde99@gmail.com',
          'permissions': [],
          'last_login': '2018-12-30 15:31:31',
          'created_at': '2018-12-04 13:07:25',
          'updated_at': '2018-12-30 15:31:31',
          'deleted_at': null,
          'name': 'Akhil Gadde',
          'username': 'akhilgadde',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 481,
        'active': 'yes',
        'name': 'Neeraj Gajula',
        'email': 'npgajula@gmail.com',
        'since': 1542398400000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 481, 'location_id': 2 }
        }],
        'code': 'STN0000029',
        'joined_on': '2nd Dec 2018',
        'credits': 4,
        'user': {
          'id': 1133,
          'email': 'npgajula@gmail.com',
          'permissions': [],
          'last_login': '2018-12-30 14:07:13',
          'created_at': '2018-11-30 21:09:06',
          'updated_at': '2018-12-30 14:07:13',
          'deleted_at': null,
          'name': 'Neeraj Praneeth Gajula',
          'username': 'neerajpraneethgajula',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'IB Physics HL',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 480,
        'active': 'yes',
        'name': 'kathyayini thota',
        'email': 'kathyayinithota@gmail.com',
        'since': 1543176000000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 480, 'location_id': 2 }
        }],
        'code': 'STK0000031',
        'joined_on': '26th Nov 2018',
        'credits': 79,
        'user': {
          'id': 1104,
          'email': 'kathyayinithota@gmail.com',
          'permissions': [],
          'last_login': '2018-11-09 14:44:21',
          'created_at': '2018-11-09 12:33:00',
          'updated_at': '2018-11-09 14:44:21',
          'deleted_at': null,
          'name': 'kathyayini thota',
          'username': 'kathyayinithota',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'math, english, business studies, french, economics, ICT',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 479,
        'active': 'yes',
        'name': 'Sodum Aarav Reddy',
        'email': 'Deepika.chalasani@gmail.com',
        'since': 1542398400000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 479, 'location_id': 7 }
        }],
        'code': 'STS0000084',
        'joined_on': '24th Nov 2018',
        'credits': 4,
        'user': {
          'id': 1130,
          'email': 'Deepika.chalasani@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-24 10:29:31',
          'updated_at': '2018-11-24 10:29:31',
          'deleted_at': null,
          'name': 'Sodum Aarav Reddy',
          'username': 'sodumaaravreddy',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'English',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 478,
        'active': 'yes',
        'name': 'Chetan Dasari',
        'email': 'chetandasari28@gmail.com',
        'since': 1543003200000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 478, 'location_id': 7 }
        }],
        'code': 'STC0000007',
        'joined_on': '18th Nov 2018',
        'credits': 1,
        'user': {
          'id': 1119,
          'email': 'chetandasari28@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-17 14:15:45',
          'updated_at': '2018-11-17 14:15:45',
          'deleted_at': null,
          'name': 'Chetan Dasari',
          'username': 'chetandasari',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': 'other',
          'what_learn': 'English writing skills ( Grammar, punctuation, word formation, pronunciation, Reading and creative writing )',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 477,
        'active': 'yes',
        'name': 'PRANITH BOALLY',
        'email': 'harini.boally@gmail.com',
        'since': 1542484800000,
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 477, 'location_id': 2 }
        }],
        'code': 'STP0000033',
        'joined_on': '17th Nov 2018',
        'credits': 26,
        'user': {
          'id': 1118,
          'email': 'harini.bollampally@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-17 09:10:26',
          'updated_at': '2018-11-17 09:10:26',
          'deleted_at': null,
          'name': 'PRANITH BOLLAMPALLY',
          'username': 'pranithbollampally',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'SSAT ENGLISH SYLLABUS UPTO FEBRUARY 1st 2019',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }],
      'meta': {
        'pagination': {
          'total': 460,
          'count': 20,
          'per_page': 20,
          'current_page': 1,
          'total_pages': 23,
          'links': { 'next': 'https://ahamlearning.com/ahamapi/common/learners?page=2' }
        }
      }
    },
    location: null,
    locations: [
      {
        'id': 1,
        'name': 'Aham Learning Hub @ Manikonda',
        'slug': 'aham-learning-hub-at-manikonda',
        'street_address': 'Mitti\'s Building, 3rd Floor,  Plot No. 19, Manikonda, Rajendra Nagar, Hyderabad.',
        'landmark': 'Near Lanco Incubation Centre',
        'city_id': 1,
        'created_at': '2016-09-08 21:36:34',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 2,
        'name': 'Aham Learning Hub @ Gachibowli',
        'slug': 'aham-learning-hubatgachibowli',
        'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
        'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
        'city_id': 1,
        'created_at': '2016-09-08 21:38:51',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 4,
        'name': 'Aham Learning Hub @ Online Engagement',
        'slug': 'aham-learning-hub-at-online-engagement',
        'street_address': 'No Real location involved',
        'landmark': 'Not Applicable',
        'city_id': 1,
        'created_at': '2016-11-02 06:37:35',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 6,
        'name': 'Aham Learning Hub @ BanjaraHills',
        'slug': 'ahamatbanjara',
        'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
        'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
        'city_id': 1,
        'created_at': '2018-01-21 13:48:36',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 7,
        'name': 'Aham Learning Hub @ Kukatpally',
        'slug': 'ahamlearninghubatkukatpally',
        'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
        'landmark': 'Above Pista House',
        'city_id': 1,
        'created_at': '2018-07-05 12:40:38',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 253,
        'name': 'Aham Certified Location @ 1132 Chancery Way, San Ramon, CA, USA',
        'slug': 'certifiedlocationatsanramon',
        'street_address': '1132 Chancery Way, San Ramon, CA, USA',
        'landmark': 'Walking Distance From Windemere Ranch Middle School',
        'city_id': 4,
        'created_at': '2019-01-03 12:32:04',
        'type': 'certified_hub',
        'city': { 'name': 'San Ramon', 'id': 4 }
      }, {
        'id': 8,
        'name': 'Aham Learning Hub @ India Online Virtual Hub',
        'slug': 'ahamlearninghubatindiaonlinevirtualhub',
        'street_address': null,
        'landmark': null,
        'city_id': 0,
        'created_at': '2018-12-17 15:00:26',
        'type': 'online_virtual_hub',
        'city': null
      }, {
        'id': 239,
        'name': 'Aham Learning Hub @ United States Of America Online Virtual Hub',
        'slug': 'ahamlearninghubatunitedstatesofamericaonlinevirtualhub',
        'street_address': null,
        'landmark': null,
        'city_id': 0,
        'created_at': '2018-12-17 15:00:32',
        'type': 'online_virtual_hub',
        'city': null
      }
    ],
    searchString: null,
    isActive: false,
    isAll: false,
    dialog: false,
    selected: null
  }),
  computed: {
    getLabel () {
      const type = this.isCardType ? 'Card' : 'Table'
      return 'View Type: ' + type
    }
  },
  methods: {
    edit (item) {
      this.selected = JSON.parse(item)
      this.dialog = true
    },
    save () {
      this.dialog = false
    }
  }
}
</script>

<style scoped>
.layout .flex {
  padding: 8px;
}
</style>
