<template>
  <div>
    <v-layout wrap row justify-center>
      <v-flex xs4>
        <v-autocomplete v-model="location" :items="locations" item-text="name"
                        item-value="name" menu-props="auto" label="Select Location" hide-details
                        clearable single-line></v-autocomplete>
      </v-flex>
      <v-flex xs4>
        <v-text-field v-model="searchString" placeholder="Search by name or email..."></v-text-field>
      </v-flex>
      <v-flex align-self-center>
        <v-btn color="primary">
          <v-icon>search</v-icon>
          Search
        </v-btn>
      </v-flex>
      <v-flex align-self-center>
        <v-switch v-model="isActive" label="Active" color="primary"></v-switch>
      </v-flex>
      <v-flex align-self-center>
        <v-checkbox v-model="isAll" label="All" color="primary"></v-checkbox>
      </v-flex>
    </v-layout>

    <v-layout row wrap>
      <v-flex xs12 sm4 v-for="(learner, i) in learners.data" :key="i">
        <v-card height="100%">
          <v-card-title class="pr-0">
            <span class="headline">{{learner.name}}</span>
            <v-spacer></v-spacer>
            <v-menu offset-y bottom left>
              <v-btn slot="activator" icon>
                <v-icon>more_vert</v-icon>
              </v-btn>

              <v-list>
                <v-list-tile @click="edit(learner)">
                  <v-list-tile-title>Edit</v-list-tile-title>
                </v-list-tile>
              </v-list>
            </v-menu>
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-layout row wrap>
              <v-flex shrink align-self-center>
                <v-img :src="learner.avatar" width="40px" height="40px" contain></v-img>
              </v-flex>
              <v-flex grow align-self-center>
                <p class="subheading font-weight-bold mb-0">{{learner.name}}</p>
                <span>{{learner.email}}</span>
              </v-flex>
            </v-layout>
          </v-card-text>
          <v-card-text class="pt-0">
            <v-layout row wrap>
              <v-flex shrink align-self-center>
                <v-icon>event_available</v-icon>
              </v-flex>
              <v-flex align-self-center>
                <p class="my-0">{{learner.since}}</p>
              </v-flex>
            </v-layout>
            <v-layout row wrap>
              <v-flex shrink align-self-center>
                <v-icon>location_searching</v-icon>
              </v-flex>
              <v-flex align-self-center>
                <p class="my-0">Home Location(s):</p>
                <p class="my-0" v-for="(location, k) in learner.preferred_locations" :key="k">{{location.name}}</p>
              </v-flex>
            </v-layout>
            <v-layout row wrap>
              <v-flex shrink align-self-center>
                <v-icon>location_on</v-icon>
              </v-flex>
              <v-flex align-self-center>
                <p class="my-0">Country: {{learner.country.name}}</p>
              </v-flex>
            </v-layout>
            <v-layout row wrap>
              <v-flex shrink align-self-center>
                <v-icon>done_outline</v-icon>
              </v-flex>
              <v-flex align-self-center>
                <span class="py-1 px-2 active white--text"
                      v-bind:class="{'activated': learner.active === 'yes', 'inactivated': learner.active !== 'yes'}">active: {{learner.active}}</span>
              </v-flex>
            </v-layout>
          </v-card-text>
        </v-card>
      </v-flex>
    </v-layout>

    <v-dialog v-model="dialog" width="500">
      <LearnerModal
        :item="selected"
        :isShow="dialog"
        @close="dialog = false"
        @save="save"/>
    </v-dialog>
  </div>
</template>

<script>
import LearnerModal from '../../components/Modal/LearnerModal'
export default {
  name: 'Learners',
  components: { LearnerModal },
  data: () => ({
    learners: {
      'data': [{
        'id': 492,
        'active': 'yes',
        'name': 'Sohan Reddy',
        'email': 'sohanreddyg@gmail.com',
        'since': '13 Jan 2019',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 492, 'location_id': 2 }
        }],
        'code': 'STS0000089',
        'joined_on': '13th Jan 2019',
        'credits': 8,
        'user': {
          'id': 1167,
          'email': 'sohanreddyg@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2019-01-11 17:54:16',
          'updated_at': '2019-01-13 11:51:54',
          'deleted_at': null,
          'name': 'Sohan Reddy',
          'username': 'sohan1',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Physics',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 491,
        'active': 'yes',
        'name': 'Siddharth Tripurani',
        'email': 'sidboss03@gmail.com',
        'since': '13 Jan 2019',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 491, 'location_id': 2 }
        }],
        'code': 'STS0000088',
        'joined_on': '13th Jan 2019',
        'credits': 8,
        'user': {
          'id': 1168,
          'email': 'sidboss03@gmail.com',
          'permissions': [],
          'last_login': '2019-01-13 15:13:20',
          'created_at': '2019-01-11 17:56:25',
          'updated_at': '2019-01-13 15:13:20',
          'deleted_at': null,
          'name': 'Siddharth Tripurani',
          'username': 'siddharthtripurani',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Physics',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 489,
        'active': 'yes',
        'name': 'Sristhuthi',
        'email': 'kcsristhuthi@gmail.com',
        'since': '31 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 489, 'location_id': 7 }
        }],
        'code': 'STS0000086',
        'joined_on': '31st Dec 2018',
        'credits': 0,
        'user': {
          'id': 1160,
          'email': 'kcsristhuthi@gmail.com',
          'permissions': [],
          'last_login': '2019-01-12 22:47:53',
          'created_at': '2018-12-30 11:33:54',
          'updated_at': '2019-01-12 22:47:53',
          'deleted_at': null,
          'name': 'Sristhuthi',
          'username': 'sristhuthi',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 488,
        'active': 'yes',
        'name': 'Takalla Vikranth',
        'email': 'temporaryemail@abcd.com',
        'since': '22 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 488, 'location_id': 6 }
        }],
        'code': 'STT0000022',
        'joined_on': '22nd Dec 2018',
        'credits': 9,
        'user': {
          'id': 1151,
          'email': 'temporaryemail@abcd.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-22 16:25:02',
          'updated_at': '2018-12-22 16:25:02',
          'deleted_at': null,
          'name': 'Takalla Vikranth',
          'username': 'takallavikranth',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'English and other subjects',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 487,
        'active': 'yes',
        'name': 'sai chandan k',
        'email': 'konreddysai@gmail.com',
        'since': '22 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 487, 'location_id': 6 }
        }],
        'code': 'STS0000085',
        'joined_on': '22nd Dec 2018',
        'credits': 5,
        'user': {
          'id': 1150,
          'email': 'konreddysai@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-22 16:14:44',
          'updated_at': '2018-12-22 16:14:44',
          'deleted_at': null,
          'name': 'sai chandan k',
          'username': 'saichandank',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 486,
        'active': 'yes',
        'name': 'Rushil Sureen',
        'email': 'kirtisureen@yahoo.co.in',
        'since': '16 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 486, 'location_id': 2 }
        }],
        'code': 'STR0000035',
        'joined_on': '16th Dec 2018',
        'credits': 0,
        'user': {
          'id': 1145,
          'email': 'kirtisureen@yahoo.co.in',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-16 14:32:38',
          'updated_at': '2018-12-16 14:32:38',
          'deleted_at': null,
          'name': 'Rushil Sureen',
          'username': 'rushilsureen',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'English,Math',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 485,
        'active': 'yes',
        'name': 'parthavi reddy',
        'email': 'parthavireddy29@gmail.com',
        'since': '11 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 2 }
        }, {
          'id': 4,
          'name': 'Aham Learning Hub @ Online Engagement',
          'slug': 'aham-learning-hub-at-online-engagement',
          'code': 'ALH0000003',
          'street_address': 'No Real location involved',
          'landmark': 'Not Applicable',
          'city_id': 1,
          'country_id': null,
          'pincode': 500008,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2016-11-02 06:37:35',
          'updated_at': '2016-11-02 06:37:35',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#89E5E3',
          'frontend_slug': 'aham-engagement',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 4 }
        }, {
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 485, 'location_id': 6 }
        }],
        'code': 'STP0000034',
        'joined_on': '11th Dec 2018',
        'credits': 9,
        'user': {
          'id': 1144,
          'email': 'parthavireddy29@gmail.com',
          'permissions': [],
          'last_login': '2018-12-19 00:38:25',
          'created_at': '2018-12-11 16:07:36',
          'updated_at': '2018-12-19 00:38:25',
          'deleted_at': null,
          'name': 'parthavi reddy',
          'username': 'parthavireddy',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'i am interested in biology and chemistry',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 484,
        'active': 'yes',
        'name': 'Lava Premal Reddy Panta',
        'email': 'alekyap@yahoo.com',
        'since': '08 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 484, 'location_id': 2 }
        }],
        'code': 'STL0000004',
        'joined_on': '8th Dec 2018',
        'credits': 10,
        'user': {
          'id': 1138,
          'email': 'alekyap@yahoo.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-12-05 09:58:25',
          'updated_at': '2018-12-05 09:58:25',
          'deleted_at': null,
          'name': 'Lava Premal Reddy Panta',
          'username': 'lavapremalreddypanta',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'Spanish',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 483,
        'active': 'yes',
        'name': 'Nimish Ray',
        'email': 'ray.nimish@gmail.com',
        'since': '04 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 483, 'location_id': 2 }
        }],
        'code': 'STN0000030',
        'joined_on': '4th Dec 2018',
        'credits': 4,
        'user': {
          'id': 1136,
          'email': 'ray.nimish@gmail.com',
          'permissions': [],
          'last_login': '2019-01-13 17:08:41',
          'created_at': '2018-12-03 17:58:23',
          'updated_at': '2019-01-13 17:08:41',
          'deleted_at': null,
          'name': 'Nimish Ray',
          'username': 'nimishray',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'Math, Physics, and chemistry',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 482,
        'active': 'yes',
        'name': 'Akhil Gadde',
        'email': 'akhilgadde99@gmail.com',
        'since': '04 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 482, 'location_id': 2 }
        }],
        'code': 'STA0000092',
        'joined_on': '4th Dec 2018',
        'credits': 0,
        'user': {
          'id': 1137,
          'email': 'akhilgadde99@gmail.com',
          'permissions': [],
          'last_login': '2018-12-30 15:31:31',
          'created_at': '2018-12-04 13:07:25',
          'updated_at': '2018-12-30 15:31:31',
          'deleted_at': null,
          'name': 'Akhil Gadde',
          'username': 'akhilgadde',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 481,
        'active': 'yes',
        'name': 'Neeraj Praneeth Gajula',
        'email': 'npgajula@gmail.com',
        'since': '02 Dec 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 481, 'location_id': 2 }
        }],
        'code': 'STN0000029',
        'joined_on': '2nd Dec 2018',
        'credits': 4,
        'user': {
          'id': 1133,
          'email': 'npgajula@gmail.com',
          'permissions': [],
          'last_login': '2018-12-30 14:07:13',
          'created_at': '2018-11-30 21:09:06',
          'updated_at': '2018-12-30 14:07:13',
          'deleted_at': null,
          'name': 'Neeraj Praneeth Gajula',
          'username': 'neerajpraneethgajula',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'IB Physics HL',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 480,
        'active': 'yes',
        'name': 'kathyayini thota',
        'email': 'kathyayinithota@gmail.com',
        'since': '26 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 480, 'location_id': 2 }
        }],
        'code': 'STK0000031',
        'joined_on': '26th Nov 2018',
        'credits': 79,
        'user': {
          'id': 1104,
          'email': 'kathyayinithota@gmail.com',
          'permissions': [],
          'last_login': '2018-11-09 14:44:21',
          'created_at': '2018-11-09 12:33:00',
          'updated_at': '2018-11-09 14:44:21',
          'deleted_at': null,
          'name': 'kathyayini thota',
          'username': 'kathyayinithota',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'math, english, business studies, french, economics, ICT',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 479,
        'active': 'yes',
        'name': 'Sodum Aarav Reddy',
        'email': 'Deepika.chalasani@gmail.com',
        'since': '24 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 479, 'location_id': 7 }
        }],
        'code': 'STS0000084',
        'joined_on': '24th Nov 2018',
        'credits': 4,
        'user': {
          'id': 1130,
          'email': 'Deepika.chalasani@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-24 10:29:31',
          'updated_at': '2018-11-24 10:29:31',
          'deleted_at': null,
          'name': 'Sodum Aarav Reddy',
          'username': 'sodumaaravreddy',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': 'English',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 478,
        'active': 'yes',
        'name': 'Chetan Dasari',
        'email': 'chetandasari28@gmail.com',
        'since': '18 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 478, 'location_id': 7 }
        }],
        'code': 'STC0000007',
        'joined_on': '18th Nov 2018',
        'credits': 1,
        'user': {
          'id': 1119,
          'email': 'chetandasari28@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-17 14:15:45',
          'updated_at': '2018-11-17 14:15:45',
          'deleted_at': null,
          'name': 'Chetan Dasari',
          'username': 'chetandasari',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': 'other',
          'what_learn': 'English writing skills ( Grammar, punctuation, word formation, pronunciation, Reading and creative writing )',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 477,
        'active': 'yes',
        'name': 'PRANITH BOLLAMPALLY',
        'email': 'harini.bollampally@gmail.com',
        'since': '17 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 477, 'location_id': 2 }
        }],
        'code': 'STP0000033',
        'joined_on': '17th Nov 2018',
        'credits': 26,
        'user': {
          'id': 1118,
          'email': 'harini.bollampally@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-17 09:10:26',
          'updated_at': '2018-11-17 09:10:26',
          'deleted_at': null,
          'name': 'PRANITH BOLLAMPALLY',
          'username': 'pranithbollampally',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '5-8',
          'what_learn': 'SSAT ENGLISH SYLLABUS UPTO FEBRUARY 1st 2019',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 476,
        'active': 'yes',
        'name': 'sri samhitha',
        'email': 'tpschowdary@gmail.com',
        'since': '16 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 476, 'location_id': 7 }
        }],
        'code': 'STS0000083',
        'joined_on': '16th Nov 2018',
        'credits': 1,
        'user': {
          'id': 1117,
          'email': 'tpschowdary@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-16 14:52:13',
          'updated_at': '2018-11-18 12:27:36',
          'deleted_at': null,
          'name': 'sri samhitha',
          'username': 'srisamhitha',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 475,
        'active': 'yes',
        'name': 'Dennis',
        'email': 'denissaden@outlook.com',
        'since': '12 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [],
        'code': 'STD0000011',
        'joined_on': '12th Nov 2018',
        'credits': 0,
        'user': {
          'id': 1109,
          'email': 'denissaden@outlook.com',
          'permissions': [],
          'last_login': '2019-01-04 11:53:46',
          'created_at': '2018-11-11 13:50:16',
          'updated_at': '2019-01-04 11:53:46',
          'deleted_at': null,
          'name': 'Dennis',
          'username': 'dennis',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': 'Working_Professional',
          'what_learn': null,
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 474,
        'active': 'yes',
        'name': 'Vennela Juluri',
        'email': 'jmadhulata@gmail.com',
        'since': '10 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 7,
          'name': 'Aham Learning Hub @ Kukatpally',
          'slug': 'ahamlearninghubatkukatpally',
          'code': 'ALH0000004',
          'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
          'landmark': 'Above Pista House',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500072,
          'latitude': 0,
          'longitude': 0,
          'deleted_at': null,
          'created_at': '2018-07-05 12:40:38',
          'updated_at': '2019-01-12 14:20:13',
          'locality_id': 5,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 1,
          'color': '#fffaff',
          'frontend_slug': 'aham-kukatpally',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 474, 'location_id': 7 }
        }],
        'code': 'STV0000030',
        'joined_on': '10th Nov 2018',
        'credits': 0,
        'user': {
          'id': 1107,
          'email': 'jmadhulata@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-10 12:29:19',
          'updated_at': '2018-11-10 12:29:19',
          'deleted_at': null,
          'name': 'Vennela Juluri',
          'username': 'vennelajuluri',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': '9-12',
          'what_learn': '10th Grade \r\nCBSE\r\nScience',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 473,
        'active': 'yes',
        'name': 'jitendra Sharma',
        'email': 'jksharma2612@gmail.com',
        'since': '03 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 6,
          'name': 'Aham Learning Hub @ BanjaraHills',
          'slug': 'ahamatbanjara',
          'code': 'AHA0000000',
          'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
          'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500034,
          'latitude': -0.0040000000000000036,
          'longitude': 0.002,
          'deleted_at': null,
          'created_at': '2018-01-21 13:48:36',
          'updated_at': '2019-01-12 16:09:42',
          'locality_id': 4,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#9295CC',
          'frontend_slug': 'aham-banjara-hills',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 473, 'location_id': 6 }
        }],
        'code': 'STJ0000018',
        'joined_on': '3rd Nov 2018',
        'credits': 1,
        'user': {
          'id': 1099,
          'email': 'jksharma2612@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-03 14:56:03',
          'updated_at': '2018-11-03 14:56:03',
          'deleted_at': null,
          'name': 'jitendra Sharma',
          'username': 'jitendrasharma',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': 'Working_Professional',
          'what_learn': 'Spoken English',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }, {
        'id': 472,
        'active': 'yes',
        'name': 'Yuvan Neerati',
        'email': 'purnima.yellowpoint@gmail.com',
        'since': '03 Nov 2018',
        'avatar': 'https://res.cloudinary.com/ahamlearning/image/upload/c_thumb,h_80,w_80/aham_icon_m6ljr5.jpg',
        'lifetime': null,
        'preferred_locations': [{
          'id': 2,
          'name': 'Aham Learning Hub @ Gachibowli',
          'slug': 'aham-learning-hubatgachibowli',
          'code': 'ALH0000001',
          'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
          'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
          'city_id': 1,
          'country_id': 1,
          'pincode': 500008,
          'latitude': 17.419,
          'longitude': 78.375,
          'deleted_at': null,
          'created_at': '2016-09-08 21:38:51',
          'updated_at': '2019-01-12 14:20:29',
          'locality_id': 2,
          'active': 1,
          'currency_type': 'INR',
          'credits_type': 'global',
          'repeat_class': 0,
          'color': '#E9B2D3',
          'frontend_slug': 'aham-gachibowli',
          'type': 'aham_learning_hub',
          'tutor_id': null,
          'pivot': { 'student_id': 472, 'location_id': 2 }
        }],
        'code': 'STY0000005',
        'joined_on': '3rd Nov 2018',
        'credits': 0,
        'user': {
          'id': 1098,
          'email': 'purnima.yellowpoint@gmail.com',
          'permissions': [],
          'last_login': null,
          'created_at': '2018-11-03 12:42:48',
          'updated_at': '2018-11-03 12:42:48',
          'deleted_at': null,
          'name': 'Yuvan Neerati',
          'username': 'yuvanneerati',
          'who_are_you': 'user',
          'interested_in': 'student',
          'photo': null,
          'locality_id': null,
          'city_id': 1,
          'mobile': null,
          'interested_subjects': null,
          'interested_subcategories': null,
          'linkedin': null,
          'resume_file': null,
          'current_profession': null,
          'why_teacher': null,
          'grade': 'other',
          'what_learn': 'Robotics',
          'public_profile': null,
          'description': null,
          'gender': null,
          'birthday': null,
          'Aadhar_card': null,
          'pan_card': null,
          'form_16': null,
          'cheque': null,
          'school': null,
          'country_id': 1,
          'picture': null,
          'country': {
            'id': 1,
            'name': 'India',
            'slug': 'india',
            'code': 'IN',
            'deleted_at': null,
            'created_at': '2018-12-17 15:00:26',
            'updated_at': '2019-01-12 12:57:03',
            'currency': 'INR',
            'current_price_per_credit': 1100,
            'status': 1
          }
        },
        'country': {
          'id': 1,
          'name': 'India',
          'slug': 'india',
          'code': 'IN',
          'deleted_at': null,
          'created_at': '2018-12-17 15:00:26',
          'updated_at': '2019-01-12 12:57:03',
          'currency': 'INR',
          'current_price_per_credit': 1100,
          'status': 1
        }
      }],
      'meta': {
        'pagination': {
          'total': 460,
          'count': 20,
          'per_page': 20,
          'current_page': 1,
          'total_pages': 23,
          'links': { 'next': 'https://ahamlearning.com/ahamapi/common/learners?page=2' }
        }
      }
    },
    location: null,
    locations: [
      {
        'id': 1,
        'name': 'Aham Learning Hub @ Manikonda',
        'slug': 'aham-learning-hub-at-manikonda',
        'street_address': 'Mitti\'s Building, 3rd Floor,  Plot No. 19, Manikonda, Rajendra Nagar, Hyderabad.',
        'landmark': 'Near Lanco Incubation Centre',
        'city_id': 1,
        'created_at': '2016-09-08 21:36:34',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 2,
        'name': 'Aham Learning Hub @ Gachibowli',
        'slug': 'aham-learning-hubatgachibowli',
        'street_address': 'Synergy Building, 3rd Floor, Plot No: 6-11, Survey No. 40, Above Andhra Bank, Khajaguda,  Naga Hills Rd, Madhura Nagar Colony, Gachibowli, Hyderabad',
        'landmark': 'Synergy Building, Andhra Bank, Near Delhi Public School',
        'city_id': 1,
        'created_at': '2016-09-08 21:38:51',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 4,
        'name': 'Aham Learning Hub @ Online Engagement',
        'slug': 'aham-learning-hub-at-online-engagement',
        'street_address': 'No Real location involved',
        'landmark': 'Not Applicable',
        'city_id': 1,
        'created_at': '2016-11-02 06:37:35',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 6,
        'name': 'Aham Learning Hub @ BanjaraHills',
        'slug': 'ahamatbanjara',
        'street_address': '8-2-682/B/5, Rd Number 12, Anand Banjara Colony, Banjara Hills, Hyderabad, Telangana 500034',
        'landmark': 'Opposite to Kaman, Above Kotak Mahindra Bank,',
        'city_id': 1,
        'created_at': '2018-01-21 13:48:36',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 7,
        'name': 'Aham Learning Hub @ Kukatpally',
        'slug': 'ahamlearninghubatkukatpally',
        'street_address': 'Above Pista House, Near JNTU Metro Station, Kukatpally, Hyderabad.',
        'landmark': 'Above Pista House',
        'city_id': 1,
        'created_at': '2018-07-05 12:40:38',
        'type': 'aham_learning_hub',
        'city': { 'name': 'Hyderabad, India', 'id': 1 }
      }, {
        'id': 253,
        'name': 'Aham Certified Location @ 1132 Chancery Way, San Ramon, CA, USA',
        'slug': 'certifiedlocationatsanramon',
        'street_address': '1132 Chancery Way, San Ramon, CA, USA',
        'landmark': 'Walking Distance From Windemere Ranch Middle School',
        'city_id': 4,
        'created_at': '2019-01-03 12:32:04',
        'type': 'certified_hub',
        'city': { 'name': 'San Ramon', 'id': 4 }
      }, {
        'id': 8,
        'name': 'Aham Learning Hub @ India Online Virtual Hub',
        'slug': 'ahamlearninghubatindiaonlinevirtualhub',
        'street_address': null,
        'landmark': null,
        'city_id': 0,
        'created_at': '2018-12-17 15:00:26',
        'type': 'online_virtual_hub',
        'city': null
      }, {
        'id': 239,
        'name': 'Aham Learning Hub @ United States Of America Online Virtual Hub',
        'slug': 'ahamlearninghubatunitedstatesofamericaonlinevirtualhub',
        'street_address': null,
        'landmark': null,
        'city_id': 0,
        'created_at': '2018-12-17 15:00:32',
        'type': 'online_virtual_hub',
        'city': null
      }
    ],
    searchString: null,
    isActive: false,
    isAll: false,
    dialog: false,
    selected: null
  }),
  methods: {
    edit (item) {
      this.selected = item
      this.dialog = true
    },
    save () {
      this.dialog = false
    }
  }
}
</script>

<style scoped>
.layout .flex {
  padding: 8px;
}

.active {
  border-radius: 4px;
}

.activated {
  background: #34bfa3;
}

.inactivated {
  background: #f4516c;
}
</style>
